### PR TITLE
Add Opt.Value to allow separate menu.Option display text vs. value

### PR DESCRIPTION
**Pull request by jamesboswell**
**This is a breaking change.**  So completely understand if you reject.

Just wanted to inform you I forked your package, and added a Value string to the Opt struct,  updated the various functions, etc.   

This allows creation of menus with "user friendly" display text (Opt.Text) but underlying long or complicated values (Opt.Value)
```
0) NOC
1) NetOps
2) Security
3) SysOps
....

// where underlying values could be anything else, for example:
Opt.ID == 0
Opt.Text == "NOC"
Opt.Value == "ou=NOC,ou=People,ou=ACME,dc=example,dc=com"
```
My specific case I wanted to prompt the user for LDAP information,  but I wanted a "friendlier" Opt.Text,  but be able to pass specific value.   Probably could have done this with func() call,  but I was unable to make that work with a loop iteration to dynamically build my menus

I have **not** added specific test cases for Opt.Value, but did updated menu_test  to ensure everything passes with new function parameter (value)

### CODE REVIEW

**Comment by dixonwille** [comment]
I will look over it this weekend. Glad to see it is getting some use! Sounds great but I agree it is difficult to decide because it is a breaking change. Maybe a new version?
On Jun 3, 2016 6:03 PM, James Boswell <notifications@github.com> wrote:This is a breaking change.  So completely understand if you reject.

Just wanted to inform you I forked your package, and added a Value string to the Opt struct,  updated the various functions, etc.   

This allows creation of menus with "user friendly" display text (Opt.Text) but underlying long or complicated values (Opt.Value)

0) NOC
1) NetOps
2) Security
3) SysOps
....

// where underlying values could be anything else, for example:
Opt.ID == 0
Opt.Text == "NOC"
Opt.Value == "ou=NOC,ou=People,ou=ACME,dc=example,dc=com"


My specific case I wanted to prompt the user for LDAP information,  but I wanted a "friendlier" Opt.Text,  but be able to pass specific value.   Probably could have done this with func() call,  but I was unable to make that work with a loop iteration to dynamically build my menus

I have not added specific test cases for Opt.Value, but did update menu_test  to ensure everything passes with new function parameter (value)



You can view, comment on, or merge this pull request online at:
  https://github.com/dixonwille/wmenu/pull/6

Commit Summary
Add Opt.Value to allow separate display (Opt.Text) vs Option value

File Changes

    M
    menu.go
    (8)
  
    M
    menu_test.go
    (104)
  
    M
    option.go
    (4)
  

Patch Links:
https://github.com/dixonwille/wmenu/pull/6.patchhttps://github.com/dixonwille/wmenu/pull/6.diff

**Comment by jamesboswell** [comment]
@dixonwille  sounds good.  Yeah,  probably a new version.   Thank you for the package,  it helped me get my project done!

**Comment by dixonwille** [comment]
Code looks good I am going to pull this down and run test and coverage

**Comment by dixonwille** [comment]
@jamesboswell `import "gopkg.in/dixonwille/wmenu.v2"` I am going to add this to the readme but I want to make sure you understand. You must import this package with this url. It allows me to use tags for different versioning. Sorry for the inconvenience but helps me out a lot. Have not merged in because I wanted to make sure I could do this in the same repo. I'll keep you posted

**Comment by dixonwille** [comment]
One Question, I am thinking it would be more useful to have the options value be an empty interface, that way any model, string, int can be passed in. It is up to the user to cast to type when retrieving it though? Thoughts? Would this mess you up?

**Comment by dixonwille** [comment]
@jamesboswell Check [this](https://godoc.org/gopkg.in/dixonwille/wmenu.v2#example-package--OptionValue) out to help explain what I mean. But Thanks for the input!!

**Comment by jamesboswell** [comment]
@dixonwille, sorry been out on holiday.  Yes `interface{}` would be better, it was a quick hack-up for me.  Looks good!

**Pull request merged**
